### ISSUE TITLE
php-simple-html-dom-parser for PHP7.3 +

### ISSUE THREAD

**Issue by WebSergeevDima** [sunra/php-simple-html-dom-parser#75]
If you use php 7.3 and higher, then use my edits. Otherwise, you will get errors due to migration to PCRE2 in new versions of PHP. 

For example: Warning: preg_match_all (): Compilation failed: invalid range in character class at offset 4

[New file](https://github.com/WebSergeevDima/php-simple-html-dom-parser/blob/master/simple_html_dom.php)

**Comment by ldim87** [comment]
Yep, it's the new strict PCRE2 caused by regex 
```
\w-:
```
which should be 
```
\w\-:
```

Here is the simple snippet used in php.net
```
preg_match('/[\w-.]+/', ''); // this will not work in PHP7.3
preg_match('/[\w\-.]+/', ''); // the hyphen need to be escaped
```
