### ISSUE TITLE
PHP 7.4

### ISSUE THREAD

**Issue by Quadratica** [sunra/php-simple-html-dom-parser#84]
Does the library work with PHP 7.4 ? Cause i get some error, in the past i already used the Php Simple Html Parser and everything was all right.

**Comment by EduVillas** [comment]
Me too
Notice: Trying to access array offset on value of type int in .../vendor/phpoffice/phpspreadsheet/src/PhpSpreadsheet/Cell/DefaultValueBinder.php on line 58

**Comment by malsatin** [comment]
Hi there.
Getting exception `preg_match(): Compilation failed: invalid range in character class at offset 4` on php 7.4.
Anyone else got that?

**Comment by mce1978** [comment]
Same here, it doesn't work! Found out that this project is abandoned. Use this fork instead.

[Kub-AT/php-simple-html-dom-parser](https://github.com/Kub-AT/php-simple-html-dom-parser)

**Comment by Quadratica** [comment]
Thank you

**Comment by prayal1711** [comment]
Just a \ needs to be added before all the hyphens in the regex defined in file simple_html_dom.php ( 2 lines to be specific )

**Comment by GitIDHere** [comment]
The fix has yet to be implemented into the repo. Had to manually edit the source scrip to get rid of the error. Don't think this fix will get added in as the repo hasn't been updated in years....

Had to add a `\` infront of all the `-` hyphens on here:

`$pattern = "/([\w-:\*]*)(?:\#([\w-]+)|\.([\w-]+))?(?:\[@?(!?[\w-:]+)(?:([!*^$]?=)[\"']?(.*?)[\"']?)?\])?([\/, ]+)/is";`

`if (!preg_match("/^[\w-:]+$/", $tag))`

**Comment by minhvuong0505** [comment]
Thanh you
