### PR TITLE
fix regex character class order in simple_html_dom.php

### PR DESCRIPTION
**Pull request by tony-dunlop**
The order of the dashes in character classes is affected by later versions of PHP, changing the order of the character ranges fixes the problem, have shortcodes after any dashes.

I noticed when upgrading to 7.4.3

the problem is explained here
https://stackoverflow.com/a/24767090/2831388

causes a couple of errors:
`Compilation failed: invalid range in character class at offset 4` in simple_html_dom.php on line 1378

and a similar error on line 696

### CODE REVIEW

File: Src/Sunra/PhpSimple/simplehtmldom_1_5/simple_html_dom.php [hunk 1]
```diff
@@ -693,7 +693,7 @@ protected function parse_selector($selector_string) {
 // This implies that an html attribute specifier may start with an @ sign that is NOT captured by the expression.
 // farther study is required to determine of this should be documented or removed.
 //        $pattern = "/([\w-:\*]*)(?:\#([\w-]+)|\.([\w-]+))?(?:\[@?(!?[\w-]+)(?:([!*^$]?=)[\"']?(.*?)[\"']?)?\])?([\/, ]+)/is";
-        $pattern = "/([\w-:\*]*)(?:\#([\w-]+)|\.([\w-]+))?(?:\[@?(!?[\w-:]+)(?:([!*^$]?=)[\"']?(.*?)[\"']?)?\])?([\/, ]+)/is";
+        $pattern = "/([-:\*\w]*)(?:\#([-\w]+)|\.([-\w]+))?(?:\[@?(!?[-\w:]+)(?:([!*^$]?=)[\"']?(.*?)[\"']?)?\])?([\/, ]+
```
Comment (silvanu) [inline Src/Sunra/PhpSimple/simplehtmldom_1_5/simple_html_dom.php:696]: You gonna get an error without `;` at the end of line.
